### ISSUE TITLE
Currencies return back in a random order

### ISSUE THREAD

**Issue by tutman96** [CVarisco/crypto-chrome-ext#2]
It looks like depending on what order the apis come back in determines the order in which they are displayed. If I want to just quickly click and glance for a specific coin, I can't look in the same place every time.

A potential solution to this would be to use a sort on the entities when each one is returned.

**Comment by CVarisco** [comment]
Hi @tutman96,
thank you for your support 👍 

Yes, you are right!
In the next release, there will be ordered in the same way every time.

Thank you again!

**Comment by CVarisco** [comment]
I published a new version (v0.0.2) where the speed on the startup should be improved (if slow now, is because the API is slow).
And also, now the order is always the same.

Tell me if do you like it and if there will be other issues 👍
